spring.application.name=hospital-gateway
server.port=8080

# URLs de los servicios
service.auth.url=http://localhost:8081
service.patient.url=http://localhost:8082
service.notification.url=http://localhost:8083
